// ==UserScript==
// @name        Dark Mode for Canvas
// @namespace    http://google.com
// @version      0.1
// @description  Adds a cool dark mode to Canvas
// @author       camila314
// @match        https://fisd.instructure.com/*
// @grant        none
// ==/UserScript==
!function(){function c(o,r,e){try{for(var l=document.querySelectorAll(o),a=0;a<l.length;a++)l[a].style[r]=e}catch(o){}}function t(o,r,e){try{document.querySelector(o).style[r]=e}catch(o){}}window.oof=function(){var o="#00ff00",r="black",e="#222222",l="#333333",a="#444444",n="#ffffff";t("#wrapper","backgroundColor",r),t("#breadcrumbs","backgroundColor",r),t(".icon-hamburger","color","#00ffff"),t("#header","backgroundColor","#121223"),t("#section-tabs-header-subtitle","color",n),t("#content-wrapper","backgroundColor",e),t(".header-bar","backgroundColor",e),t("#context_modules","backgroundColor",l),t("#context_modules_sortable_container","borderColor",l),t("#context_modules_sortable_container","borderRadius","0.5em"),t("#context_modules_sortable_container","backgroundColor",e),t("#ag-list","backgroundColor",l),t("#ag-list","borderColor",l),t("#announcements_on_home_page","color",o),t(".todo-list-header","backgroundColor",o),t("#dashboard_header_container div","backgroundColor",a),t("#dashboard_header_container div","color",o),t(".tray-with-space-for-global-nav div","backgroundColor",l),t(".tray-with-space-for-global-nav div h2","color",o),t("tbody.fc-body","backgroundColor",l),t(".discussions-v2__wrapper","backgroundColor",l),t(".unpinned-discussions-v2__wrapper","backgroundColor",e),t(".closed-for-comments-discussions-v2__wrapper","backgroundColor",e),c(".recent-activity-text-container","color",n),c(".MlJlv_btWg","color",o),c(".tray-with-space-for-global-nav div div","color",n),c(".planner-day","backgroundColor",l),c(".planner-day","color",o),c(".planner-day","borderRadius","1em"),c(".title_3bek","backgroundColor",l),c(".course-options a","color",e),c(".ig-row","backgroundColor",a),c(".ig-title","color",o),c(".ig-details","color",n),c("#left-side a","color",o),c(".ellipsible","color",o),c(".ellipsis","color",n),c(".ellipsis .name","color",o),c(".context_module_item div","borderColor",n),c(".context_module_item div ","backgroundColor",a),setTimeout(window.oof,1)},window.oof()}();
